// Pega esto dentro de tu archivo data.js reemplazando el navLinksData anterior
 const navLinksData = [
  {
    isActive: true,
    name: "INICIO",
    href: "/",
    // subMenu: ["iPhone 16", "iPhone 15", "iPhone 14", "iPhone 13", "Reacondicionados"],
  },
  {
    isActive: false,
    name: "PRODUCTOS",
    href: "/products",
    subMenu: ["Fundas & Forros", "Cargadores MagSafe", "AirPods", "Protectores de pantalla"],
  },
  {
    isActive: false,
    name: "SERVICIOS",
    href: "/#services",
    // subMenu: ["Cambio de pantalla", "Batería", "Diagnóstico gratis", "Agua & golpes"],
  },
  {
    isActive: false,
    name: "OFERTAS",
    href: "/product",
  },
  {
    isActive: false,
    name: "CONTACTO",
    href: "/contact",
  },
];


const filterButtonsData = [
  { name: "TODOS",        count: 6,  isActive: true },
  { name: "CELULARES",    count: 3 },
  { name: "AURICULARES",  count: 2 },
  { name: "SMARTWATCHES", count: 1 },
];

const productData = [
  {
    id: "iphone-15-pro",
    name: "IPHONE 15 PRO",
    brand: "Apple",
    price: 1199.00,
    tag: "NUEVO",
    category: "CELULARES",
    bg: "#e8e4de",
    img: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=85",
      "https://images.unsplash.com/photo-1696446702183-a98d8dd8e9e8?w=800&q=85",
      "https://images.unsplash.com/photo-1678911820864-e2c567c655d7?w=800&q=85",
    ],
    colors: ["#1c1c1e", "#e8e4de", "#4a90d9", "#6e5a4e"],
    colorNames: ["Negro Titanio", "Titanio Natural", "Azul Titanio", "Titanio Blanco"],
    storage: ["128 GB", "256 GB", "512 GB", "1 TB"],
    description: "El iPhone 15 Pro lleva el rendimiento al máximo con el chip A17 Pro, cámara de 48 MP y el revolucionario botón de acción. Titanio de grado aeroespacial.",
    specs: [
      { label: "Pantalla",  value: '6.1" Super Retina XDR, 2556 x 1179' },
      { label: "Chip",      value: "A17 Pro — 6 núcleos" },
      { label: "Cámara",    value: "48 MP principal + 12 MP ultra + 12 MP tele" },
      { label: "Batería",   value: "Hasta 23 h reproducción de video" },
      { label: "5G",        value: "Sí — sub‑6 GHz y mmWave" },
      { label: "Puerto",    value: "USB‑C con USB 3" },
      { label: "SO",        value: "iOS 17" },
    ],
  },
  {
    id: "galaxy-s24",
    name: "GALAXY S24",
    brand: "Samsung",
    price: 999.00,
    tag: "MÁS VENDIDO",
    category: "CELULARES",
    bg: "#1c1c1e",
    img: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=85",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=85",
    ],
    colors: ["#1c1c1e", "#d4af37", "#a8c5da", "#e8e4de"],
    colorNames: ["Negro Ónix", "Amber Yellow", "Cobalt Violet", "Marble Gray"],
    storage: ["128 GB", "256 GB"],
    description: "Galaxy S24 con Galaxy AI integrada. Fotografía nocturna sin límites y la pantalla Dynamic AMOLED más brillante del mercado.",
    specs: [
      { label: "Pantalla",  value: '6.2" Dynamic AMOLED 2X, 2340 x 1080' },
      { label: "Chip",      value: "Snapdragon 8 Gen 3 for Galaxy" },
      { label: "Cámara",    value: "50 MP + 12 MP + 10 MP" },
      { label: "Batería",   value: "4000 mAh, carga rápida 25W" },
      { label: "5G",        value: "Sí" },
      { label: "RAM",       value: "8 GB" },
      { label: "SO",        value: "Android 14 — One UI 6.1" },
    ],
  },
  {
    id: "pixel-9-pro",
    name: "PIXEL 9 PRO",
    brand: "Google",
    price: 849.00,
    tag: null,
    category: "CELULARES",
    bg: "#d6e4f0",
    img: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=85",
    ],
    colors: ["#2d2d2d", "#e8d5c4", "#4a7c6f"],
    colorNames: ["Obsidiana", "Porcelana", "Salvia Verde"],
    storage: ["128 GB", "256 GB", "512 GB"],
    description: "La magia de Google Tensor G4 y la mejor cámara computacional del mercado. IA real, fotos reales, experiencia pura.",
    specs: [
      { label: "Pantalla",  value: '6.3" LTPO OLED, 2856 x 1280' },
      { label: "Chip",      value: "Google Tensor G4" },
      { label: "Cámara",    value: "50 MP + 48 MP ultrawide + 48 MP tele" },
      { label: "Batería",   value: "4700 mAh, carga 30W" },
      { label: "5G",        value: "Sí" },
      { label: "RAM",       value: "16 GB" },
      { label: "SO",        value: "Android 14 — Pixel UI" },
    ],
  },
  {
    id: "airpods-pro-2",
    name: "AIRPODS PRO 2",
    brand: "Apple",
    price: 249.00,
    tag: "OFERTA",
    category: "AURICULARES",
    bg: "#f5f5f5",
    img: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=800&q=85",
      "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800&q=85",
    ],
    colors: ["#f5f5f5"],
    colorNames: ["Blanco"],
    storage: [],
    description: "Cancelación de ruido activa de próxima generación. Audio adaptativo que evoluciona según tu entorno en tiempo real.",
    specs: [
      { label: "Chip",       value: "H2" },
      { label: "ANC",        value: "Activa personalizada" },
      { label: "Batería",    value: "6 h + 24 h con estuche MagSafe" },
      { label: "Resistencia",value: "IP54 auriculares y estuche" },
      { label: "Audio",      value: "Espacial personalizado con seguimiento dinámico" },
    ],
  },
  {
    id: "apple-watch-s9",
    name: "APPLE WATCH S9",
    brand: "Apple",
    price: 399.00,
    tag: null,
    category: "SMARTWATCHES",
    bg: "#2c2c2e",
    img: "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=800&q=85",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=85",
    ],
    colors: ["#1c1c1e", "#e8e4de", "#e74c3c", "#f39c12"],
    colorNames: ["Medianoche", "Plateado", "Rojo (PRODUCT)RED", "Amarillo"],
    storage: [],
    description: "El Apple Watch más brillante. Chip S9 SiP, pantalla siempre activa y el revolucionario gesto de doble toque.",
    specs: [
      { label: "Pantalla",   value: "LTPO OLED Retina siempre activa, 2000 nits" },
      { label: "Chip",       value: "S9 SiP dual-core de 64 bits" },
      { label: "Salud",      value: "Frec. cardíaca, ECG, SpO₂, temperatura" },
      { label: "Batería",    value: "Hasta 18 h — 36 h modo bajo consumo" },
      { label: "Resistencia",value: "WR50, IP6X, resistente a golpes" },
    ],
  },
  {
    id: "galaxy-buds3-pro",
    name: "GALAXY BUDS3 PRO",
    brand: "Samsung",
    price: 179.00,
    tag: "NUEVO",
    category: "AURICULARES",
    bg: "#e8f4e8",
    img: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=85",
    ],
    colors: ["#f5f5f5", "#1c1c1e"],
    colorNames: ["Silver Shadow", "Onyx Black"],
    storage: [],
    description: "Sonido Hi-Fi con cancelación de ruido inteligente. Los auriculares Galaxy más avanzados con forma de ala rediseñada.",
    specs: [
      { label: "Drivers",    value: "2-way con tweeter dedicado" },
      { label: "ANC",        value: "Inteligente adaptativa" },
      { label: "Batería",    value: "6 h + 21 h con estuche" },
      { label: "Resistencia",value: "IPX7 auriculares, IPX4 estuche" },
      { label: "Audio",      value: "360 Audio con Dolby Head Tracking" },
    ],
  },
];


const productLinksData = [
  {
    title: "Product",
    links: ["Womenswear", "Menswear", "Kids", "Sale", "Discover"],
  },
];
const buyingLinksData = [
  {
    title: "Buying",
    links: [
      "Shipping",
      "Returns",
      "Terms of Use",
      "Privacy Policy",
      "Customer Service",
    ],
  },
];
const socialLinksData = [
  {
    title: "Social",
    links: ["Instagram", "Facebook", "Twitter"],
  },
];


const newSeasonData = [
  {
    name: "IPHONE 16 PRO",
    price: "$1,299.00",
    tag: "NUEVO",
    bg: "#e8e4de",
    img: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80",
  },
  {
    name: "GALAXY S25 ULTRA",
    price: "$1,199.00",
    tag: "NUEVO",
    bg: "#1c1c1e",
    img: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80",
  },
  {
    name: "PIXEL 9 PRO",
    price: "$999.00",
    tag: null,
    bg: "#d6e4f0",
    img: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80",
  },
  {
    name: "AIRPODS PRO 2",
    price: "$249.00",
    tag: "OFERTA",
    bg: "#f0f0f0",
    img: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=600&q=80",
  },
  {
    name: "APPLE WATCH S10",
    price: "$449.00",
    tag: "NUEVO",
    bg: "#2c2c2e",
    img: "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600&q=80",
  },
  {
    name: "GALAXY BUDS 3",
    price: "$199.00",
    tag: null,
    bg: "#e8f4e8",
    img: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80",
  },
  {
    name: "XIAOMI 14 ULTRA",
    price: "$899.00",
    tag: "NUEVO",
    bg: "#f5e6e8",
    img: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80",
  },
  {
    name: "ONEPLUS 13",
    price: "$799.00",
    tag: null,
    bg: "#e6f0e8",
    img: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600&q=80",
  },
];

export const carruselData = [
  {
    id: 1,
    img: "/images/audifonos.png",       // ← tu ruta aquí
    titulo: "20% OFF en iPhone",
    subtitulo: "Solo este fin de semana",
    cta: "Ver oferta",
    ctaHref: "/ofertas",
    bg: "#1c1c1e",                    // color de fondo mientras carga
  },
  {
    id: 2,
    img: "/images/tablet.png",
    titulo: "Nueva temporada Samsung",
    subtitulo: "Galaxy S24 ya disponible",
    cta: "Comprar ahora",
    ctaHref: "/celulares/samsung",
    bg: "#1a2332",
  },
  {
    id: 3,
    img: "/images/promo1.png",
    titulo: "Accesorios premium",
    subtitulo: "AirPods, cables y más",
    cta: "Ver accesorios",
    ctaHref: "/accesorios",
    bg: "#2a2a2a",
  },
  {
    id: 4,
    img: "/images/promo2.png",
    titulo: "Envío gratis",
    subtitulo: "En compras mayores a $500",
    cta: "Explorar",
    ctaHref: "/ofertas",
    bg: "#0f1923",
  },
];


export const testimonialsData = [
  {
    id: 1,
    name: "Carlos M.",
    location: "Ciudad de México",
    avatar: "CM",
    rating: 5,
    date: "Enero 2025",
    title: "Increíble calidad",
    comment: "Superó todas mis expectativas. La pantalla es espectacular y la batería dura todo el día sin problema. Lo recomiendo al 100%.",
    product: "iPhone 15 Pro",
    verified: true,
  },
  {
    id: 2,
    name: "Sofía R.",
    location: "Guadalajara",
    avatar: "SR",
    rating: 5,
    date: "Febrero 2025",
    title: "Mejor compra del año",
    comment: "Llegó en perfectas condiciones y antes de lo esperado. La cámara toma fotos increíbles incluso de noche. Muy contenta con mi compra.",
    product: "Galaxy S24",
    verified: true,
  },
  {
    id: 3,
    name: "Andrés P.",
    location: "Monterrey",
    avatar: "AP",
    rating: 4,
    date: "Enero 2025",
    title: "Muy buen producto",
    comment: "El rendimiento es excelente, corre todo sin lag. Solo le doy 4 estrellas porque el cargador no viene incluido, pero el equipo vale cada peso.",
    product: "Pixel 9 Pro",
    verified: true,
  },
  {
    id: 4,
    name: "Valentina G.",
    location: "Bogotá",
    avatar: "VG",
    rating: 5,
    date: "Diciembre 2024",
    title: "Lo uso todo el día",
    comment: "Uso los AirPods en el gym, en el trabajo y en casa. El sonido es limpio, la cancelación de ruido es brutal y la batería no me ha fallado.",
    product: "AirPods Pro 2",
    verified: true,
  },
  {
    id: 5,
    name: "Miguel T.",
    location: "Lima",
    avatar: "MT",
    rating: 5,
    date: "Febrero 2025",
    title: "Exactamente lo que buscaba",
    comment: "La pantalla del Watch S9 es muy clara y el monitoreo de salud funciona perfecto. Ya no salgo a correr sin él. Excelente inversión.",
    product: "Apple Watch S9",
    verified: true,
  },
  {
  id: 6,
  name: "Laura C.",
  location: "Madrid",
  avatar: "LC",
  rating: 5,
  date: "Marzo 2025",
  title: "Rápido y potente",
  comment: "La fluidez del sistema es impresionante. Puedo editar videos y jugar sin ningún problema. La batería me dura más de lo que esperaba.",
  product: "iPhone 15 Pro",
  verified: true,
},
{
  id: 7,
  name: "Diego H.",
  location: "Santiago",
  avatar: "DH",
  rating: 4,
  date: "Febrero 2025",
  title: "Excelente cámara",
  comment: "Las fotos salen súper nítidas y el zoom es una locura. Le doy 4 estrellas solo porque el precio es algo elevado, pero vale la pena.",
  product: "Galaxy S24",
  verified: true,
},
{
  id: 8,
  name: "Camila F.",
  location: "Buenos Aires",
  avatar: "CF",
  rating: 5,
  date: "Marzo 2025",
  title: "Diseño premium",
  comment: "El acabado se siente de alta gama y el rendimiento es impecable. Todo funciona rápido y sin trabas.",
  product: "Pixel 9 Pro",
  verified: true,
},
{
  id: 9,
  name: "Jorge L.",
  location: "Ciudad de México",
  avatar: "JL",
  rating: 5,
  date: "Enero 2025",
  title: "Sonido espectacular",
  comment: "La cancelación de ruido es increíble. Los uso para trabajar y realmente me ayudan a concentrarme. Totalmente recomendados.",
  product: "AirPods Pro 2",
  verified: true,
},
{
  id: 10,
  name: "Daniela V.",
  location: "Medellín",
  avatar: "DV",
  rating: 5,
  date: "Marzo 2025",
  title: "Perfecto para entrenar",
  comment: "El seguimiento de actividad es muy preciso y la batería me dura varios días. Se ha vuelto parte esencial de mi rutina.",
  product: "Apple Watch S9",
  verified: true,
},
{
  id: 11,
  name: "Ricardo S.",
  location: "Monterrey",
  avatar: "RS",
  rating: 4,
  date: "Febrero 2025",
  title: "Gran rendimiento",
  comment: "Muy rápido en multitarea y excelente calidad de pantalla. Solo mejoraría el tiempo de carga, pero en general estoy muy satisfecho.",
  product: "iPhone 15 Pro",
  verified: true,
},
{
  id: 12,
  name: "Paula M.",
  location: "Quito",
  avatar: "PM",
  rating: 5,
  date: "Marzo 2025",
  title: "Vale cada peso",
  comment: "Desde que lo tengo, todo es más práctico. Funciona perfecto, la batería rinde bastante y la experiencia es muy fluida.",
  product: "Galaxy S24",
  verified: true,
},
{
  id: 13,
  name: "Fernando A.",
  location: "Guadalajara",
  avatar: "FA",
  rating: 5,
  date: "Febrero 2025",
  title: "Me sorprendió",
  comment: "No esperaba tanto por el precio. Es rápido, toma excelentes fotos y el diseño es muy elegante.",
  product: "Pixel 9 Pro",
  verified: true,
},
{
  id: 14,
  name: "Natalia E.",
  location: "Lima",
  avatar: "NE",
  rating: 5,
  date: "Enero 2025",
  title: "Comodidad total",
  comment: "Son súper cómodos incluso después de horas de uso. El audio es claro y potente. Definitivamente volvería a comprarlos.",
  product: "AirPods Pro 2",
  verified: true,
},
{
  id: 15,
  name: "Sebastián R.",
  location: "Bogotá",
  avatar: "SR",
  rating: 4,
  date: "Marzo 2025",
  title: "Muy funcional",
  comment: "Me ayuda a mantenerme activo y monitorear mi salud fácilmente. Solo me gustaría que la batería durara un poco más.",
  product: "Apple Watch S9",
  verified: true,
},
];




export {
  navLinksData,
  filterButtonsData,
  productData,
  socialLinksData,
  newSeasonData,
  buyingLinksData,
  productLinksData,
};
